---
# tasks file for elasticsearch

- name: ADD YUM REPOSITORY
  yum_repository:
    name: "{{ item }}"
    description: "{{ item }} repository for {{ elk_stack_version }}.x packages"
    baseurl: "{{ repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ gpgkey_url }}"
    enabled: yes
  with_items:
    - "{{ elk_services }}"
    
- name: INSTALL ELK SERVICES
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ elk_services }}"

- name: START ELK SERVICES
  service: 
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - "{{ elk_services }}"

- name: CHANGE ELASTICSEARCH CONFIGURATION
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#network.host'
    line: 'network.host: localhost'
    backrefs: yes
  notify: RESTART ELASTICSEARCH

- name: CHANGE KIBANA CONFIGURATION
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^#server.host:', line: "server.host: {{ ansible_eth0.ipv4.address }}" }
    - { regexp: '^#server.port:', line: "server.port: {{ service_port }}" }
  notify: RESTART KIBANA

- name: CHANGE OPENSSL CONFIG
  lineinfile:
    dest: /etc/pki/tls/openssl.cnf
    insertbefore: '^# Extensions for a typical CA'
    line: "subjectAltName = IP: {{ ansible_eth0.ipv4.address }}"

- name: GENERATE SSL CERTIFICATE
  shell: "openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/{{ ssl_certificate_name }}.key -out certs/{{ ssl_certificate_name }}.crt"
  args:
    chdir: /etc/pki/tls
    creates: "/etc/pki/tls/certs/{{ ssl_certificate_name }}.crt"

- name: COPY SSL CERTIFICATE TO LOCAL MACHINE
  fetch:
    src:  "/etc/pki/tls/certs/{{ ssl_certificate_name }}.crt"
    dest: "./"
    flat: yes

- name: COPY LOGSTASH CONFIGS
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
  with_fileglob:
    - logstash/*
  notify: RESTART LOGSTASH

- name: DOWNLOAD KIBANA DASHBOARDS FOR FILEBEAT
  unarchive:
    src: "{{ beats_dashboard_url }}"
    dest: "{{ path_to_kibana_dashboards }}"
    remote_src: True

- name: INSTALL DASHBOARDS
  shell: ./load.sh
  args:
    chdir: "{{ path_to_kibana_dashboards }}/{{ beats_dashboard_name }}"

- name: LOAD FILEBEAT INDEX TEMPLATE
  uri:
    url: http://localhost:9200/_template/filebeat?pretty
    method: PUT
    body: "{{ lookup('file','filebeat-index-template.json') }}"
    body_format: json

- name: CREATE CONFIG FOR FILEBEAT
  template:
    src: filebeat_config.j2
    dest: roles/filebeat/files/filebeat.yml
  vars:
    elk_private_ip_address: "{{ ansible_eth0.ipv4.address }}"
  delegate_to: 127.0.0.1

